blank_issues_enabled: false
contact_links:
  - name: Microsoft Developer Community [New]
    url: https://developercommunity.visualstudio.com/loadtesting
    about: We are no longer monitoring new issues on this repo is. Please create an issue on Developer Community.
