name: Sync issue to Azure DevOps work item

on: 
  issues:
    types:
      [opened, edited, closed, reopened]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: ninallam/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "devdiv"
          ado_project: "OnlineServices"
          ado_area_path: "OnlineServices\\CloudTestingService"
          ado_iteration_path: "OnlineServices\\Copper\\CY22 Q2\\2022-05"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: false
          log_level: 100
